import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Layout from '../components/Layout'
import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    { label: 'Home', href: '/' },
    { label: 'Trips', href: '/trips' },
    { label: 'Contact', href: '/contact' }
  ]
  const footer = [
    {
      heading: 'Links',
      links: [
        { label: 'Home', href: '/' },
        { label: 'Trips', href: '/trips' },
        { label: 'Contact', href: '/contact' }
      ]
    }
  ]
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Layout navLinks={navLinks} footer={footer}>{children}</Layout>
      </body>
    </html>
  );
}
